name: Release

on:
  push:
    branches:
      - main

jobs:
  checks:
    uses: ./.github/workflows/ci.yaml

  pages:
    uses: ./.github/workflows/pages.yaml
    needs: [checks]

  version-and-publish:
    name: Release
    runs-on: ubuntu-latest
    needs: [checks]
    permissions:
      contents: write # Required to create github releases
      issues: write # Required by semantic-release
      pull-requests: write # Required by semantic-release
      id-token: write # Required for OIDC npm publishing

    steps:
      - name: Checkout Code
        uses: actions/checkout@v6
        with:
          fetch-depth: 0 # Fetch all history for release notes and tags

      - name: Setup CI Environment
        uses: ./.github/actions/setup-ci

      - name: Build
        run: pnpm build:lib

      - name: Semantic Release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: pnpm exec semantic-release
