name: Deployment

on:
  push:
    branches:
      - main

jobs:
  checks:
    uses: ./.github/workflows/ci.yaml
  version-and-publish:
    # This job handles versioning and publishing
    name: Version & Publish
    runs-on: ubuntu-latest
    needs: [checks]
    if: github.ref == 'refs/heads/main' && github.event_name == 'push'

    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/setup-ci

      # This is the core of the Changesets action
      - name: Create Version PR or Publish to npm
        id: changesets
        uses: changesets/action@v1
        with:
          # This command will run 'pnpm changeset version' and create a PR
          version: 'pnpm changeset version'
          # This command will run 'pnpm publish' if a new version was released
          publish: 'pnpm publish --no-git-checks'
        env:
          # This is used to create the "Version Packages" PR
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          # This is used to publish to the npm registry
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
