name: Changeset

on:
  push:
    branches:
      - main

jobs:
  checks:
    uses: ./.github/workflows/ci.yaml
    # Don't run checks if only versioning happened
    if: 'github.event.head_commit.message != "chore: version packages"'

  pages:
    # Deploy every push, except versioning (when no checks)
    uses: ./.github/workflows/pages.yaml
    needs: [checks]

  version-and-publish:
    name: Version & Publish
    runs-on: ubuntu-latest
    needs: [checks]
    if: always() && needs.checks.result != 'failure'

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - uses: ./.github/actions/setup-ci

      - name: Version and Create Release Pull Request
        id: changesets
        uses: changesets/action@v1
        with:
          commit: 'chore: version packages'
          createGithubReleases: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
