# Runs checks on every pull request
name: Integration

on:
  pull_request:
    branches:
      - main
  workflow_call:

jobs:
  checks-run:
    name: Checks
    runs-on: ubuntu-latest
    if: github.event_name == 'workflow_call' || github.ref_name != 'changeset-release/main'
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/setup-ci

      - name: Caches
        uses: actions/cache@v4
        with:
          path: |
            .cache/.eslintcache
            .cache/.prettier-cache
          key: ${{ runner.os }}-checks-${{ hashFiles('**/pnpm-lock.yaml') }}

      - name: Generate svelte configs
        run: pnpm svelte-kit sync

      - name: Run Prettier style check
        run: pnpm prettier --check --cache --cache-location=.cache/.prettier-cache --cache-strategy content .

      - name: Run ESLint
        env:
          NODE_OPTIONS: '--max-old-space-size=4096'
        run: pnpm eslint --cache --cache-location=.cache/.eslintcache --cache-strategy content .

      - name: Svelte check
        run: pnpm svelte-check --tsconfig ./tsconfig.json

  test-run:
    name: Run Tests
    runs-on: ubuntu-latest
    if: github.event_name == 'workflow_call' || github.ref_name != 'changeset-release/main'
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/setup-ci

      - name: Cache Vitest
        uses: actions/cache@v4
        with:
          path: .cache/.vite
          key: ${{ runner.os }}-vitest-${{ hashFiles('**/pnpm-lock.yaml') }}
          restore-keys: |
            ${{ runner.os }}-vitest-

      - name: Generate svelte configs
        run: pnpm svelte-kit sync

      - name: Run tests
        run: pnpm test

  check-changeset-run:
    # This job runs checks on PRs to ensure a changeset file is included if needed
    name: Check for Changeset
    runs-on: ubuntu-latest
    if: github.event_name == 'pull_request' && github.ref_name != 'changeset-release/main'

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - uses: ./.github/actions/setup-ci

      - name: Check for changeset file
        run: 'pnpm changeset status --since origin/main'

  checks-skip:
    name: Checks
    runs-on: ubuntu-latest
    if: github.ref_name == 'changeset-release/main'
    steps:
      - run: echo "Pull request is a version bump, skip checks"

  test-skip:
    name: Run Tests
    runs-on: ubuntu-latest
    if: github.ref_name == 'changeset-release/main'
    steps:
      - run: echo "Pull request is a version bump, skip tests"

  check-changeset-skip:
    name: Check for Changeset
    runs-on: ubuntu-latest
    if: github.ref_name == 'changeset-release/main'
    steps:
      - run: echo "Pull request is a version bump, skip changeset checks"
