# Runs checks on every pull request
name: Integration

on:
  pull_request:
    branches:
      - main
  workflow_call:

jobs:
  checks:
    name: Checks
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v6

      - name: Setup CI Environment
        uses: ./.github/actions/setup-ci

      - name: Restore Caches
        uses: actions/cache@v5
        with:
          path: |
            .cache/.eslintcache
            .cache/.prettier-cache
          key: ${{ runner.os }}-checks-${{ hashFiles('**/pnpm-lock.yaml') }}

      - name: Run Linting and Type Checks
        env:
          NODE_OPTIONS: '--max-old-space-size=4096'
        run: |
          pnpm svelte-kit sync
          pnpm prettier --check --cache --cache-location=.cache/.prettier-cache --cache-strategy content .
          pnpm eslint --cache --cache-location=.cache/.eslintcache --cache-strategy content .
          pnpm svelte-check --tsconfig ./tsconfig.json

  tests:
    name: Run Tests
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v6

      - name: Setup CI Environment
        uses: ./.github/actions/setup-ci

      - name: Restore Vitest Cache
        uses: actions/cache@v5
        with:
          path: .cache/.vite
          key: ${{ runner.os }}-vitest-${{ hashFiles('**/pnpm-lock.yaml') }}
          restore-keys: |
            ${{ runner.os }}-vitest-

      - name: Run Unit Tests
        run: |
          pnpm svelte-kit sync
          pnpm test
