# Runs checks on every pull request
name: Integration

on:
  pull_request:
    branches:
      - main
  workflow_call:

jobs:
  checks-run:
    name: Checks
    # This job runs for pushes/workflow calls, or for any PR NOT from the changeset branch
    if: github.event_name == 'workflow_call' || github.head_ref != 'changeset-release/main'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/setup-ci

      - name: Caches
        uses: actions/cache@v4
        with:
          path: |
            .cache/.eslintcache
            .cache/.prettier-cache
          key: ${{ runner.os }}-checks-${{ hashFiles('**/pnpm-lock.yaml') }}

      - name: Generate svelte configs
        run: pnpm svelte-kit sync

      - name: Run Prettier style check
        run: pnpm prettier --check --cache --cache-location=.cache/.prettier-cache --cache-strategy content .

      - name: Run ESLint
        env:
          NODE_OPTIONS: '--max-old-space-size=4096'
        run: pnpm eslint --cache --cache-location=.cache/.eslintcache --cache-strategy content .

      - name: Svelte check
        run: pnpm svelte-check --tsconfig ./tsconfig.json

  checks-skipped:
    name: Checks # NOTE: The name is IDENTICAL to the job above
    runs-on: ubuntu-latest
    # This job runs ONLY on PRs that ARE from the changeset branch
    if: github.event_name == 'pull_request' && github.head_ref == 'changeset-release/main'
    steps:
      - run: echo "Checks are not required for automated versioning PRs."

  test-run:
    name: Run Tests
    if: github.event_name == 'workflow_call' || github.head_ref != 'changeset-release/main'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/setup-ci

      - name: Cache Vitest
        uses: actions/cache@v4
        with:
          path: .cache/.vite
          key: ${{ runner.os }}-vitest-${{ hashFiles('**/pnpm-lock.yaml') }}

      - name: Generate svelte configs
        run: pnpm svelte-kit sync

      - name: Run tests
        run: pnpm test

  test-skipped:
    name: Run Tests # NOTE: The name is IDENTICAL
    runs-on: ubuntu-latest
    if: github.event_name == 'pull_request' && github.head_ref == 'changeset-release/main'
    steps:
      - run: echo "Tests are not required for automated versioning PRs."

  check-changeset-run:
    name: Check for Changeset
    if: github.event_name == 'workflow_call' || github.head_ref != 'changeset-release/main'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - uses: ./.github/actions/setup-ci

      - name: Check for changeset file
        run: 'pnpm changeset status --since origin/main'

  check-changeset-skipped:
    name: Check for Changeset # NOTE: The name is IDENTICAL
    runs-on: ubuntu-latest
    if: github.event_name == 'pull_request' && github.head_ref == 'changeset-release/main'
    steps:
      - run: echo "A changeset check is not required for the versioning PR itself."
